language: python
python:
- '3.7'
before_install:
- pip install poetry
install:
- poetry install
addons:
  sonarcloud:
    organization: "webdesignhma"
    token: "122b129b90d56fd180160deda5ddc04bb318c296"
script:
- poetry run pytest
- sonar-scanner -X
