language: python
python: 
    - "3.7"
before_install:
    - pip install poetry
install:
    - poetry install
addons:
    sonarcloud:
        organization: "webdesignhma" # the key of the org you chose at step #3
        token:
            secure: 479dec7364a7e1b342d3b19093fe4396965d55f0 # encrypted value of your token
        # other script steps might be done before running the actual analysis
script:
    - poetry run pytest
    - sonar-scanner -X
    
        
