language: python
python:
- '3.7'
before_install:
- pip install poetry
install:
- poetry install
addons:
  sonarcloud:
    organization: "webdesignhma"
    token: "kX9yxedQFGTnIoWVRnyxOUUIC/wWt4fltTHLjX/vbvJvkIGNjpvcjG/O1G95JfvcKAPXFDozdmQ7YWWOs+qNQ8tgaY7zNue62hqzFV+J4ndpSnxwKxJbCu8RPpvbIoLFfX6zlmM5W5lHz/Pd7uzpzy2dzXvfjg8LaQjCrMoDCRl9zU5yHByAzQ41M/lMtd/BIXpj1wUB2DUlpnouVT6tYAIgF9cfhP8vMI56NfvC6lbw/RQRbbUJYrix6x6p49R5zDZgx9c/UCmFBZUazohDeyj3POh9/A1ofsGTymaR4r2aPAeDhaRj0IccHhSV+1gJsfHnc8sIs5RHoXqsuzGrClgKbGDr+64Ai6+cpSK+MVJ/0OtiWaw8FksKMbJvAmspiAETXc7oB3H9p3DFKRsdVhuZqzYtXGva2WvEMz7tWW2ndnYAa9w/X8Pro/tteM+MSkLbhjmzhsLqK5XZB7v1ZSAD3sK/2FyEk1BTMh4W6EoKyjsWYjGEYdvt067g99Ry8goOyIO8Ftqpet79Oo7eHLuIdsAN1UfGDDQgGFcjNptvdJASMpp4oRLPrMfPLzqWGSbAdlR3FoL5xEWFs7Hnyg6S2XDzvEbkaCM7b/LYng3hORQN96CuPglf11lVJV126Wfrvt4YItfSisYDZSg79izCkWmUYFnUyyrjn41BZYE="
script:
- poetry run pytest
- sonar-scanner -x
